### PR TITLE
Add travis and appveyor support + SDL2

### PR DESCRIPTION
**Pull request by madebr**
Appveyor output: https://ci.appveyor.com/project/madebr/librw/build/1.0.154
Travis output: https://travis-ci.org/madebr/librw/builds/408196303

### CODE REVIEW

**Comment by aap** [comment]
What about the -lc -lc thing? Why is that not necessary anymore? And does dvp-as suddenly run things through cpp or what?

**Comment by madebr** [comment]
Linking twice to a lib is to solve cyclic dependencies. Putting the c lib twice in the list only makes sense if another lib is between the two occurrences.

I have to disable optimizations for ps2 to get the linker to work. (see error in initial travis log for ps2)
https://ci.appveyor.com/project/madebr/librw/build/1.0.160
https://travis-ci.org/madebr/librw/builds/413688563

**Comment by madebr** [comment]
I've added support for SDL2.
https://travis-ci.org/madebr/librw/builds/413797260
https://ci.appveyor.com/project/madebr/librw/build/1.0.167

**Comment by madebr** [comment]
You will have to create an account with travis-ci and appveyor to enable continuous integration.
They have an integration with github, so that should be easy.

**Pull request merged**
