### PR TITLE
cmake fixes: fix install + add sdl2 + add ci (using conan)

### PR DESCRIPTION
**Pull request by madebr**
Hello,

This pr fixes the following things:
- cmake did not install akk librw header files. This causes re3 not to find them.
- cmake was missing sdl2 support

This pr adds:
- a conanfile.py for *easy* downloading of dependencies + building.
  conan will handle the dependencies, independent of platform (Windows/Linux/Macos)
  (ps2 is a WIP)
  It can be used as following:
  ```bash
  # change directory to librw
  cd path/to/librw
  # create and change to build directory
  mkdir build && cd build
  # download dependencies (and build them if missing)
  conan install ..
  # build librw
  conan build ..
  ```
  conan also allows to make a local librw build tree visible to re3 using `conan create` or *editable packages*.
- add ci for the cmake script + conan using github actions.
  All valid combinations of librw platform and operating system are tested, except ps2.
  ps2 is not (yet) tested, but is a WIP.
  This is how it looks like: https://github.com/madebr/librw/actions/runs/392444660

### CODE REVIEW

**Review by ShFil119 — APPROVED** [review]
looks good

**Comment by ShFil119** [comment]
btw @madebr do you maybe plan to create conanfile for re3?

(I'm fighting now against the interpolation, I didn't have any attention for cmake lately)

**Comment by madebr** [comment]
I have created one, but it needs mpg123 which is not (yet) available for conan (but it will be soon as I have opened a pr for it).

re3 has currently a problem with a static openal: see https://github.com/GTAmodding/re3/issues/826

**Comment by ShFil119** [comment]
About mpg123: I was able to get it compiled with this cmake file. https://www.mpg123.de/cgi-bin/scm/mpg123/trunk/ports/cmake/

About this issue it should be enough to add extra check?

**Comment by madebr** [comment]
Let's move the openal discussion over to GTAmodding/re3#826

**Pull request merged**
